version: '3.9'

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - './db/data/db-files:/data/db'
      - './db/init/:/docker-entrypoint-initdb.d/'
    ports:
      - 27017:27017